### PR TITLE
#14: handle __.*__ in keys in maps

### LINKED ISSUE #14: Handle maps with keys that match regex __.*__
Firestore can't store fields with names that match the regex `__.*__`. So we need to remove these keys and replace them with something else so that the whole record doesn't fail when being persisted.

### PR DESCRIPTION
**Pull request by Alex-Schiff**
* [Firestore can't handle field names that match the regex `__.*__`](https://firebase.google.com/docs/firestore/quotas#collections_documents_and_fields).
* The change is to proactively check the 2 maps for keys that match the regex `__.*__` and drop the leading and trailing `_` characters.
* Then, when the data is retrieved, if it matches `_.*_` it will add the leading and trailing `_` back in.

Closes #14

### CODE REVIEW

File: src/test/kotlin/io/lsdconsulting/lsd/distributed/firestore/repository/ConversionsKtTest.kt [hunk 1]
```diff
@@ -146,5 +182,17 @@ internal class ConversionsKtTest {
         private fun provideDurations() = listOf(
             Arguments.of(Duration.ofDays(-1L)), Arguments.of(Duration.ZERO), Arguments.of(Duration.ofDays(1L))
         )
+
+        @JvmStatic
+        private fun provideSanitizationStrings() = listOf(
+            Arguments.of("test", "test"),
```
Comment (lukasz-gryzbon) [inline src/test/kotlin/io/lsdconsulting/lsd/distributed/firestore/repository/ConversionsKtTest.kt:188]: Should we have a case with single underscores as input?

Comment (Alex-Schiff) [reply src/test/kotlin/io/lsdconsulting/lsd/distributed/firestore/repository/ConversionsKtTest.kt:188]: Done

**Review by lukasz-gryzbon — APPROVED** [review]
